name: HTML Validation
on:
  push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check HTML5
      uses: Cyb3r-Jak3/html5validator-action@<latest version>
      with:
        root: docs
